networks:
  backend:

volumes:
  ecommercepgadmin:
  ecommercedata:

services:
  pgadmin:
    container_name: ecommerce-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@ecommerce.store}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ecommercepgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

  ecommercedata:
    container_name: ecommerce-data
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - ecommercedata:/var/lib/postgresql/data

  frontend:
    container_name: ecommerce-frontend
    image: ${DOCKER_REGISTRY-}frontend
    ports:
        - "3000:8080" 
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    networks:
        - backend

  backend:
    container_name: ecommerce-backend  
    image: ${DOCKER_REGISTRY-}backend
    ports:
        - "8000:8080"
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
        - ecommercedata
    networks:
        - backend

